export const GITHUB_URL = 'https://github.com/Real-Dev-Squad/website-my';
export const RDS_MAIN_URL = 'http://realdevsquad.com/';
export const RDS_WELCOME_URL = 'https://welcome.realdevsquad.com/';
export const RDS_EVENTS_URL = 'http://realdevsquad.com/events.html';
export const RDS_MEMBERS_URL = 'https://members.realdevsquad.com/';
export const RDS_CRYPTO_URL = 'https://crypto.realdevsquad.com/';
export const RDS_STATUS_URL = 'https://status.realdevsquad.com/';
export const LOGOUT_URL = 'https://api.realdevsquad.com/auth/signout';
export const MAIN_SITE_URL = 'https://realdevsquad.com/';
export const GOTO_URL = 'https://realdevsquad.com/goto';
export const AUTH_URL =
  'https://github.com/login/oauth/authorize?client_id=23c78f66ab7964e5ef97';
